
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres
  password: 1234

development:
  <<: *default
  database: app_developvent


test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_prodaction

